### ISSUE TITLE
One Slot Backpack

### ISSUE THREAD

**Issue by GAMELXRD** [Tynoxs/BuildersDelight#1]
After you place a block (or a full stack) in the Iron Chisel inventory, you can exit the interface and the block (full stack) will remain inside. Moreover, you can discard the Iron Chisel with the block inside or put it in the chest. The placed block inside the Iron Chisel will not go anywhere.

**Comment by Tynoxs** [comment]
Thanks for opening a ticket, it's actually not a bug and was intended, however it will be changed with version 0.9.

**Comment by GAMELXRD** [comment]
Oh, okay. Thanks for the info :D
