### ISSUE TITLE
ModelBakeEvent Issue

### ISSUE THREAD

**Issue by Gamemassa** [Tynoxs/BuildersDelight#1]
Hi,

I just tried to run Minecraft with several mods, including your Builder's Delight mod, and I got an error message saying that Builder's Delight failed to load correctly. I've attached the crash report here. Please let me know if you need anything else with it.

[crash-2022-07-09_15.27.05-fml.txt](https://github.com/Tynoxs/BuildersDelight/files/9077791/crash-2022-07-09_15.27.05-fml.txt)

**Comment by Speiger** [comment]
That is forges 64 patch breaking it.
The patch basically broke a lot of mods.
