### ISSUE TITLE
Connected textures

### ISSUE THREAD

**Issue by BenjaminLeSire** [Tynoxs/BuildersDelight#22]
Hi,

Thank you for merging the PRs. Currently, there aren't connected textures anymore. I can try to help. I can see three paths:

- not do anything, keep the textures non-connected
- update the code to do it the way it was done previously by loading custom textures (currently, my knowledge of those parts of minecraft and forge is very poor, but I can learn)
- rely on external connected textures as a soft dependency (at least three mods do it: https://legacy.curseforge.com/minecraft/mc-mods/fusion-connected-textures, https://legacy.curseforge.com/minecraft/mc-mods/ctm, https://legacy.curseforge.com/minecraft/mc-mods/athena).

Do you want me to try one of those solutions? If so, which one would you prefer?

**Comment by Tynoxs** [comment]
Hi, would you mind adding me on Discord? Username - "tynoxs".

I'd prefer this

> update the code to do it the way it was done previously by loading custom textures (currently, my knowledge of those parts of minecraft and forge is very poor, but I can learn)

but would also not mind this 

> rely on external connected textures as a soft dependency (at least three mods do it: https://legacy.curseforge.com/minecraft/mc-mods/fusion-connected-textures, https://legacy.curseforge.com/minecraft/mc-mods/ctm, https://legacy.curseforge.com/minecraft/mc-mods/athena).

**Comment by etherealgears** [comment]
Any updates on when connected textures might be added?
