### ISSUE TITLE
Compatibility Crash on Launch

### ISSUE THREAD

**Issue by dylanjkl** [Tynoxs/BuildersDelight#23]
Removing BuildersDelight fixes the issue - tested with and without.

[crash-2024-02-08_13.15.59-client.txt](https://github.com/Tynoxs/BuildersDelight/files/14209949/crash-2024-02-08_13.15.59-client.txt)

**Comment by BenjaminLeSire** [comment]
Do you think you could share your setup, for example on mediafire or wetransfer? At least the mods and config folder, to help reproduce your crash.
