### ISSUE TITLE
Game crash, I saw you wanted the log...

### ISSUE THREAD

**Issue by Swifty744** [Tynoxs/BuildersDelight#27]
https://pastebin.com/2WpLF4gQ

I can't paste it because the error log is so long. I saw you requested the log so I popped it into a pastebin, it only happeens with the latest version of builders delight.

**Comment by Tynoxs** [comment]
Thanks,

`Caused by 0: java.lang.NoClassDefFoundError: com/tynoxs/buildersdelight/content/item/BdFurnitureKit`

It's because I changed the furniture kit. 
Every Compat already fixed this. The fix will be in the next version of Every Compat.
