### ISSUE TITLE
Glass is always crafted as 'fancy'

### ISSUE THREAD

**Issue by its-cookie** [Tynoxs/BuildersDelight#30]
Minecraft 1.20.1
Forge 47.2.20
BuildersDelight-1.20.1-v.1.3

When you try to craft any type of glass (such as oak, dark oak, acacia, bamboo, etc.) within a crafting table, it always gives you the 'fancy' option, even if you click on clear, double, porthole, etc.

**Comment by Tynoxs** [comment]
This is intentional, you make the fancy glass and then change it to the desired glass using the iron chisel.
