### ISSUE TITLE
failed to load correctly

### ISSUE THREAD

**Issue by snowlee15** [Tynoxs/BuildersDelight#32]
i am trying to use the Builder's delight mod on a 1.20.4 server and im getting this error Builder's Delight (buildersdelight) has failed to load correctly
§7java.lang.NoClassDefFoundError: net/minecraft/world/level/block/GlassBlock,

**Comment by BenjaminLeSire** [comment]
The mod is currently available for 1.20.1, but not for 1.20.4. Please try with a 1.20.1 server and it should work.
