### ISSUE TITLE
server down

### ISSUE THREAD

**Issue by DocKaos1949** [Tynoxs/BuildersDelight#4]
So the 1.19 update for server side is crashing the server and wont allow me to re-load it - crash log attached
[crash-2022-07-18_20.37.15-fml.txt](https://github.com/Tynoxs/BuildersDelight/files/9151799/crash-2022-07-18_20.37.15-fml.txt)

Using newest Forge update - 1.19-41.0.100

**Comment by Tynoxs** [comment]
Thanks for reporting, this has already been reported though.
