### ISSUE TITLE
[Suggestion] Add connected textures

### ISSUE THREAD

**Issue by Nevrai** [Tynoxs/BuildersDelight#7]
I think Builder’s Delight is great, and I think it’d be even more wonderful if you could add connected textures to the blocks that don’t already appear to connect, with [ConnectedTexturesMod](https://www.curseforge.com/minecraft/mc-mods/ctm). That’d be the feature I’d most love to see in Builder’s Delight, and I’m sure many others would too.

**Comment by vindocel** [comment]
CTM has not yet updated to 1.19.2, so I don't even see an advantage in this implementation, at least for now, my opinion

**Comment by Tynoxs** [comment]
I want Builders Delight to stay a standalone mod, so no CTM. But I'll probably add more connected textures.
