### ISSUE TITLE
Unable to build furniture in survival 1.18.2

### ISSUE THREAD

**Issue by OldManMig** [Tynoxs/BuildersDelight#8]
I just downloaded this mod for the version 1.18.2 with forge, everything is working great other than the inability to figure out how to build furniture kits in survival! I have the recent version without the saw or hammer, and everything works great in creative. I would love to be able to build the furniture kits in my survival world though! Please let me know if I am just missing something super simple :) Thanks!

**Comment by Tynoxs** [comment]
Sorry for the late response, you probably figured it out by now. Below are the recipes if you still need them, this of course works for all wood variants.

![2023-01-24_19 25 53](https://user-images.githubusercontent.com/18245607/214376934-2e7e04bb-a3a8-4d6c-956f-a572374cf679.png)
![2023-01-24_19 26 06](https://user-images.githubusercontent.com/18245607/214376941-05500804-6cf7-4469-b514-163de0c4034c.png)
