### ISSUE TITLE
[1.19.2] Crash on start-up

### ISSUE THREAD

**Issue by Nevrai** [Tynoxs/BuildersDelight#9]
The game crashes on start-up with Builder’s Delight installed.

Crash report: https://pastebin.com/raw/2Yi5TCc0

### Versions

* **Minecraft:** 1.19.2 (latest)
* **Forge:** 43.1.43 (latest)
* **Builder’s Delight:** 0.9.5 (latest)

**Comment by BenjaminLeSire** [comment]
See #10 

You can build it from source if you don't feel like waiting.
